name: colorful_logger
description: A simple and customizable logger package for Flutter and Dart, adding colorful output to make debugging and log tracking easier and more efficient.
version: 1.0.1
repository: https://github.com/faizan2301/colorful_logger

environment:
  sdk: ^3.5.4

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
